# Generated by Django 5.2.17 on 2026-09-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outputs', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('type_label', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('body', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_by_label', models.CharField(max_length=254)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_by_label', models.CharField(blank=True, max_length=254)),
                ('unpublished_reason', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='outputs.output')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='outputs.outputversion')),
            ],
            options={
                'ordering': ('-published_at',),
                'indexes': [models.Index(fields=['organization', 'unpublished_at', '-published_at'], name='publication_organiz_649162_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unpublished_at__isnull', True)), fields=('organization', 'output'), name='uniq_live_publication_per_output')],
            },
        ),
    ]
