# Generated by Django 5.2.17 on 2026-10-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list)),
                ('formats', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_by_label', models.CharField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='publication.publication')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['organization', '-sent_at'], name='publication_organiz_321b7d_idx')],
            },
        ),
    ]
