# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intelligence', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSignalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_scores', to='intelligence.signal')),
            ],
            options={
                'ordering': ('organization', '-fit_score'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'signal'), name='uniq_client_score_per_signal'), models.CheckConstraint(condition=models.Q(('confidence__lte', 100), ('fit_score__lte', 100)), name='client_score_scores_lte_100')],
            },
        ),
    ]
