# Generated by Django 5.2.17 on 2026-10-03 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('enrichment', '0002_initial'),
        ('scoring', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_component', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('audience_component', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('priority_component', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('fit_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weights_used', models.JSONField(default=dict)),
                ('matches', models.JSONField(default=list)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relevance', to='enrichment.claim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_scores', to='clients.clientprofileversion')),
            ],
            options={
                'ordering': ('organization', '-fit_score'),
                'indexes': [models.Index(fields=['organization', 'profile', '-fit_score'], name='scoring_cla_organiz_3cbc37_idx')],
                'constraints': [models.UniqueConstraint(fields=('claim', 'profile'), name='uniq_claim_relevance_per_profile')],
            },
        ),
    ]
