# Generated by Django 5.2.17 on 2026-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mechanism', 'Mechanism'), ('effect', 'Effect or outcome'), ('dosage', 'Dose or protocol'), ('safety', 'Safety or interaction'), ('comparison', 'Comparison'), ('market', 'Market or product')], max_length=16)),
                ('text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('is_cited', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('content_item', 'segment'),
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('relevance_gate', 'Relevance gate'), ('extraction', 'Extraction'), ('drafting', 'Drafting')], db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Model declined'), ('invalid', 'Output failed validation'), ('errored', 'Call failed'), ('capped', 'Refused by cost cap')], max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('content_item', 'segment'),
            },
        ),
    ]
