# Generated by Django 5.2.17 on 2026-09-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrichment', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='evidence.contentitem'),
        ),
        migrations.AddField(
            model_name='claim',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='evidence.contentsegment'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='content_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='evidence.contentitem'),
        ),
        migrations.AddField(
            model_name='claim',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='enrichment.modelrun'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evidence.contentitem'),
        ),
        migrations.AddField(
            model_name='question',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='enrichment.modelrun'),
        ),
        migrations.AddField(
            model_name='question',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evidence.contentsegment'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=['purpose', '-at'], name='modelrun_purpose_at'),
        ),
    ]
