# Generated by Django 5.2.17 on 2026-09-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('sources', '0002_acquisitionprovider_providerpolicyversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('creator', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('gate_metadata', models.JSONField(blank=True, default=dict)),
                ('content_state', models.CharField(choices=[('discovered', 'Discovered'), ('metadata', 'Metadata only'), ('transcribed', 'Transcribed')], default='discovered', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('gate_decision', models.CharField(choices=[('pending', 'Not yet assessed'), ('relevant', 'Relevant'), ('rejected', 'Rejected'), ('sampled', 'Rejected but sampled')], db_index=True, default='pending', max_length=16)),
                ('gate_reason', models.TextField(blank=True)),
                ('gate_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition_route', models.CharField(blank=True, max_length=64)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='sources.providerpolicyversion')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='ingestion.ingestionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='sources.source')),
            ],
            options={
                'ordering': ('-published_at', '-discovered_at'),
            },
        ),
        migrations.CreateModel(
            name='ContentSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_char', models.PositiveIntegerField()),
                ('end_char', models.PositiveIntegerField()),
                ('start_seconds', models.FloatField(blank=True, null=True)),
                ('end_seconds', models.FloatField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='evidence.contentitem')),
            ],
            options={
                'ordering': ('content_item', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='TranscriptArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('publisher_transcript', 'Publisher transcript'), ('taddy', 'Taddy'), ('creator_captions', 'Creator captions'), ('apify_subtitles', 'Apify subtitles'), ('assemblyai', 'AssemblyAI'), ('manual', 'Manual import')], max_length=32)),
                ('text', models.TextField()),
                ('quality', models.PositiveSmallIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='evidence.contentitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_state', 'gate_decision'], name='content_state_gate'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id', 'content_hash'), name='uniq_content_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='contentsegment',
            constraint=models.UniqueConstraint(fields=('content_item', 'ordinal'), name='uniq_segment_ordinal'),
        ),
    ]
