# Generated by Django 5.2.17 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptartifact',
            name='anchors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
