# Generated by Django 5.2.17 on 2026-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('route', models.CharField(choices=[('podcast', 'Podcast'), ('youtube', 'YouTube'), ('research', 'Research'), ('social', 'Social')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='active', max_length=16)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
