# Generated by Django 5.2.17 on 2026-09-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('taddy', 'Taddy'), ('apify', 'Apify'), ('assemblyai', 'AssemblyAI'), ('ncbi', 'NCBI E-utilities'), ('crossref', 'Crossref'), ('rss', 'Direct RSS'), ('manual', 'Manual import')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('monthly_cap_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_run_max_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProviderPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('access_basis', models.TextField()),
                ('licence', models.CharField(blank=True, max_length=200)),
                ('attribution_required', models.BooleanField(default=False)),
                ('max_excerpt_chars', models.PositiveIntegerField(default=0)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('honours_deletion', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_label', models.CharField(blank=True, max_length=254)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='sources.acquisitionprovider')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='source',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='sources.providerpolicyversion'),
        ),
        migrations.AddConstraint(
            model_name='providerpolicyversion',
            constraint=models.UniqueConstraint(fields=('provider', 'version'), name='uniq_policy_version_per_provider'),
        ),
    ]
