# Generated by Django 5.2.17 on 2026-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_acquisitionprovider_providerpolicyversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionprovider',
            name='credential_ciphertext',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acquisitionprovider',
            name='credential_hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='acquisitionprovider',
            name='credential_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisitionprovider',
            name='credential_updated_by_label',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
