# Generated by Django 5.2.17 on 2026-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_provider_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='poll_interval_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
    ]
