# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'constraints': [models.CheckConstraint(condition=models.Q(('window_start__lte', models.F('window_end'))), name='digest_window_start_lte_end')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('in review', 'In review'), ('watching', 'Watching'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('needs_scientific_routing', models.BooleanField(default=False)),
                ('awaiting_operator_judgment', models.BooleanField(default=False)),
                ('domain_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ('-domain_score', 'code'),
                'indexes': [models.Index(fields=['state', 'first_seen_at'], name='signal_state_first_seen')],
                'constraints': [models.CheckConstraint(condition=models.Q(('domain_score__lte', 100)), name='signal_domain_score_lte_100')],
            },
        ),
    ]
