# Generated by Django 5.2.17 on 2026-09-21 21:26

import apps.operations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('units', models.JSONField(default=dict)),
                ('estimated_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('platform_admin', 'Platform Admin')], default='operator', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.operations.models.OperatorUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('config', 'Config'), ('review', 'Review'), ('approval', 'Approval'), ('publication', 'Publication'), ('export', 'Export'), ('system', 'System')], db_index=True, max_length=20)),
                ('actor_realm', models.CharField(choices=[('operator', 'Operator'), ('org', 'Org user'), ('system', 'System')], max_length=16)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenancy.organization')),
            ],
            options={
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['organization', '-at'], name='operations__organiz_0ece14_idx')],
            },
        ),
    ]
