# Generated by Django 5.2.17 on 2026-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costevent',
            name='estimated_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
