# Generated by Django 5.2.17 on 2026-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_costevent_estimated_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatoruser',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatoruser',
            name='totp_last_counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatoruser',
            name='totp_secret',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.BigIntegerField(db_index=True)),
                ('code_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['operator_id', 'used_at'], name='operations__operato_067d97_idx')],
            },
        ),
    ]
