# Generated by Django 5.2.17 on 2026-10-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operator_totp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backup', 'Nightly backup'), ('restore_test', 'Restore test')], db_index=True, max_length=16)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped — not configured')], max_length=16)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('artifact', models.CharField(blank=True, max_length=300)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['kind', '-started_at'], name='operations__kind_3ca918_idx')],
            },
        ),
    ]
