# Generated by Django 5.2.17 on 2026-10-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text="Why this version exists, e.g. 'Added the sleep range, Q4'.", max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_label', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ('organization', '-number'),
            },
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Product or SKU'), ('ingredient', 'Ingredient or active'), ('category', 'Category or collection'), ('service', 'Service'), ('content', 'Content property')], default='product', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('terms', models.JSONField(default=list, help_text='Words and phrases that mean this asset. Matched case-insensitively.')),
                ('weight', models.PositiveSmallIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='clients.clientprofileversion')),
            ],
            options={
                'ordering': ('organization', '-weight', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClientTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.CharField(choices=[('audience', 'Audience'), ('priority', 'Strategic priority'), ('competitor', 'Competitor')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('terms', models.JSONField(default=list)),
                ('weight', models.PositiveSmallIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='clients.clientprofileversion')),
            ],
            options={
                'ordering': ('organization', 'facet', '-weight', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='clientprofileversion',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_profile_version_per_org'),
        ),
        migrations.AddConstraint(
            model_name='clientprofileversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('organization',), name='one_current_profile_per_org'),
        ),
    ]
