# Generated by Django 5.2.17 on 2026-10-03 14:31

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Required. 'We emailed it to three addresses' is not a record.", max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('receives_outputs', models.BooleanField(default=True, help_text='Off for someone who should exist on the record but not be emailed.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_label', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ('organization', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organization'), name='uniq_contact_email_per_org')],
            },
        ),
    ]
