# Generated by Django 5.2.17 on 2026-09-21 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trend_brief', 'Trend intelligence brief'), ('content_queue', 'Monthly content queue'), ('content_brief', 'Content brief / draft'), ('product_memo', 'Product / opportunity memo'), ('research_alert', 'Research alert'), ('visibility_benchmark', 'Visibility benchmark')], max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('drafting', 'Drafting'), ('draft', 'Draft'), ('review ready', 'Review ready'), ('approved', 'Approved'), ('published', 'Published'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='drafting', max_length=20)),
                ('client_profile_version', models.CharField(blank=True, max_length=64)),
                ('domain_pack_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_label', models.CharField(max_length=254)),
                ('discipline', models.CharField(default='Scientific / legal claims', max_length=120)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to='outputs.output')),
            ],
            options={
                'ordering': ('-signed_off_at',),
            },
        ),
        migrations.CreateModel(
            name='OutputVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('drafting', 'Drafting'), ('draft', 'Draft'), ('review ready', 'Review ready'), ('approved', 'Approved'), ('published', 'Published'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_label', models.CharField(blank=True, max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='outputs.output')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approver_label', models.CharField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='outputs.outputversion')),
            ],
            options={
                'ordering': ('-approved_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='outputversion',
            constraint=models.UniqueConstraint(fields=('output', 'number'), name='uniq_version_per_output'),
        ),
    ]
