# Generated by Django 5.2.17 on 2026-10-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('html', 'Web page'), ('markdown', 'Markdown'), ('csv', 'Spreadsheet')], max_length=16)),
                ('filename', models.CharField(max_length=300)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('renderer_version', models.CharField(default='1', max_length=16)),
                ('was_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by_label', models.CharField(blank=True, max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='outputs.outputversion')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='outputs_exp_organiz_44be13_idx')],
            },
        ),
    ]
